Ext.define('MBI.view.setup.MapdefS2NtView', {
	extend: 'Ext.grid.Panel',
	
	autoScroll : true,
	
	columns : [{
		xtype	:'gridcolumn',
		dataIndex:'decimal_len',
		align:'center',
		text:'decimal_len'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_add',
		align:'center',
		text:'col_add'
	},{
		xtype:'gridcolumn',
		dataIndex:'etc',
		align:'center',
		text:'etc'
	},{
		xtype:'gridcolumn',
		dataIndex:'order_by_desc_flag',
		align:'center',
		text:'order_by_desc_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'frozen_seq_no',
		align:'center',
		text:'frozen_seq_no'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_code',
		align:'center',
		text:'col_code'
	},{
		xtype:'gridcolumn',
		dataIndex:'main_table_id_flag',
		align:'center',
		text:'main_table_id_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'seq_no',
		align:'center',
		text:'seq_no'
	},{
		xtype:'gridcolumn',
		dataIndex:'spread_level',
		align:'center',
		text:'spread_level'
	},{
		xtype:'gridcolumn',
		dataIndex:'data_type',
		align:'center',
		text:'data_type'
	},{
		xtype:'gridcolumn',
		dataIndex:'mask_edit',
		align:'center',
		text:'mask_edit'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_alias3',
		align:'center',
		text:'col_alias3'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_alias2',
		align:'center',
		text:'col_alias2'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_alias1',
		align:'center',
		text:'col_alias1'
	},{
		xtype:'gridcolumn',
		dataIndex:'func_id',
		align:'center',
		text:'func_id'
	},{
		xtype:'gridcolumn',
		dataIndex:'group_by_function',
		align:'center',
		text:'group_by_function'
	},{
		xtype:'gridcolumn',
		dataIndex:'order_by_no',
		align:'center',
		text:'order_by_no'
	},{
		xtype:'gridcolumn',
		dataIndex:'spread_id',
		align:'center',
		text:'spread_id'
	},{
		xtype:'gridcolumn',
		dataIndex:'align_type',
		align:'center',
		text:'align_type'
	},{
		xtype:'gridcolumn',
		dataIndex:'table_code',
		align:'center',
		text:'table_code'
	},{
		xtype:'gridcolumn',
		dataIndex:'save_flag',
		align:'center',
		text:'save_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'combo_data',
		align:'center',
		text:'combo_data'
	},{
		xtype:'gridcolumn',
		dataIndex:'data_size',
		align:'center',
		text:'data_size'
	},{
		xtype:'gridcolumn',
		dataIndex:'group_by_flag',
		align:'center',
		text:'group_by_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'math_function',
		align:'center',
		text:'math_function'
	},{
		xtype:'gridcolumn',
		dataIndex:'tab_text2',
		align:'center',
		text:'tab_text2'
	},{
		xtype:'gridcolumn',
		dataIndex:'tab_text1',
		align:'center',
		text:'tab_text1'
	},{
		xtype:'gridcolumn',
		dataIndex:'math_clause',
		align:'center',
		text:'math_clause'
	},{
		xtype:'gridcolumn',
		dataIndex:'tab_text3',
		align:'center',
		text:'tab_text3'
	},{
		xtype:'gridcolumn',
		dataIndex:'table_alias',
		align:'center',
		text:'table_alias'
	},{
		xtype:'gridcolumn',
		dataIndex:'dsgn_id',
		align:'center',
		text:'dsgn_id'
	},{
		xtype:'gridcolumn',
		dataIndex:'combo_display',
		align:'center',
		text:'combo_display'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_id',
		align:'center',
		text:'col_id'
	},{
		xtype:'gridcolumn',
		dataIndex:'auto_create_flag',
		align:'center',
		text:'auto_create_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'codeview_table_code',
		align:'center',
		text:'codeview_table_code'
	},{
		xtype:'gridcolumn',
		dataIndex:'codeview_table_col',
		align:'center',
		text:'codeview_table_col'
	},{
		xtype:'gridcolumn',
		dataIndex:'format_type',
		align:'center',
		text:'format_type'
	},{
		xtype:'gridcolumn',
		dataIndex:'dynamic_col',
		align:'center',
		text:'dynamic_col'
	},{
		xtype:'gridcolumn',
		dataIndex:'combo_code',
		align:'center',
		text:'combo_code'
	},{
		xtype:'gridcolumn',
		dataIndex:'col_width',
		align:'center',
		text:'col_width'
	},{
		xtype:'gridcolumn',
		dataIndex:'readonly_flag',
		align:'center',
		text:'readonly_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'link_col',
		align:'center',
		text:'link_col'
	},{
		xtype:'gridcolumn',
		dataIndex:'notnull_flag',
		align:'center',
		text:'notnull_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'table_id',
		align:'center',
		text:'table_id'
	},{
		xtype:'gridcolumn',
		dataIndex:'hidden_flag',
		align:'center',
		text:'hidden_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'default_value',
		align:'center',
		text:'default_value'
	},{
		xtype:'gridcolumn',
		dataIndex:'group_by_clause',
		align:'center',
		text:'group_by_clause'
	},{
		xtype:'gridcolumn',
		dataIndex:'lock_flag',
		align:'center',
		text:'lock_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'codeview_link_col',
		align:'center',
		text:'codeview_link_col'
	},{
		xtype:'gridcolumn',
		dataIndex:'math_flag',
		align:'center',
		text:'math_flag'
	},{
		xtype:'gridcolumn',
		dataIndex:'merge_text',
		align:'center',
		text:'merge_text'
	},{
		xtype:'gridcolumn',
		dataIndex:'display_type',
		align:'center',
		text:'display_type'
	},{
		xtype:'gridcolumn',
		dataIndex:'dynamic_col_det',
		align:'center',
		text:'dynamic_col_det'
	}]

});